### ISSUE TITLE
man page install doesn't respect $PREFIX

### ISSUE THREAD

**Issue by blippy** [matyler/mtCellEdit#2]
The mtcelledit tries to write its man page to `/usr/share/man/man1`, but it should respect `$PREFIX` as follows ...

mtcelledit/mtConf.txt:96:
`    MAN_INSTALL="/usr/share/man/man1"`
should be:
`    MAN_INSTALL="$DATA_INSTALL/man/man1"`

**Comment by matyler** [comment]
Thanks for spotting this.  I have tidied this up in this latest update.
