### ISSUE TITLE
mtpixy manpage

### ISSUE THREAD

**Issue by blippy** [matyler/mtCellEdit#3]
Similar to the previous issue, you need to set
` MAN_INSTALL="$DATA_INSTALL/man/man1"`

However, there seems to be a further issue with the `configure` file which I can't figure out; at least in v3.0. Could you please

        cd mtpixy
        ./configure --prefix=$HOME/.local

and confirm that  `MAN_INSTALL` is not pointing to `/usr/share/man/man1`.

**Comment by matyler** [comment]
Thanks for spotting this.  I fixed the mtConf.txt file for this, and a few other bits also.
