### ISSUE TITLE
[Request] Non-compressed file format

### ISSUE THREAD

**Issue by nikita-moor** [matyler/mtCellEdit#6]
Could the spreadsheet be saved not into a compressed "TSV Book" but as a directory? Exactly like the `.tsv.zip` file structure but non-compressed.

My lab software imports TSV files and I would like to edit them with comfort, preserving formulas and formatting. So, to have all advantages of the rich spreadsheet functions with easy access to the resulting data without need to extract tsv-files from the archive.

It could be useful for version-control systems (git) too.

**Comment by nikita-moor** [comment]
Unfortunately the software we use has no CLI, so "yes", I'm doing import manually. Not a big issue, but would be glad to simplify it in future. Now I'm thinking about mounting zip-file as a read-only file system, may be this be a solution…

Also, I think non-compressed file format would be VCS-friendly — kind of Flat XML (`.fods`) from LibreOffice, but with all benefits of bare TSV.

**Comment by matyler** [comment]
Even though you have to load files manually via a GUI, everything else could be put into a script.  As a test I created the following directory structure:

```
./nikita/
./nikita/test_suite.tsv.zip
./nikita/edit_file.sh
./nikita/git/
```

By running the script you can edit the file, and the script will automatically update the git repo for you when you close mtCellEdit.  You can start the script from the command line or by double clicking in a GUI file manager app like PCManFM.

The script I used is as follows:

```
#!/bin/bash

# Edit file, expand ZIP, & update git
# M.Tyler 2018-11-27

FILE=test_suite.tsv.zip

mtcelledit-qt5 $FILE

cd git
rm -rf *.tsv
unzip ../$FILE

git add . && git commit -a -m "Version $(date +%Y.%m%d.%H%M.%S)"
```

This script expands the ZIP file as soon as editing finishes so it keeps the raw files synchronized with the editable ZIP file, and all changes are tracked and timestamped using git.

I'm glad you like the speed of mtCellEdit, its one of the reasons I like it too.  It seems to load large text files quicker than a text editor!  Even though modern hardware is blazingly fast, software seems to be getting ever slower.

**Comment by nikita-moor** [comment]
Wow, thank you very much for the extensive solution of my problem, amazing work!
